version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:14.2-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
    external: true
